services:
  myportfolio:
    container_name: myportfolio
    restart: always
    image: node:20.10.0
    ports:
      - 3009:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/myportfolio
    working_dir: /usr/src/myportfolio

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
